language: scala

os:
  - osx

scala:
  - 2.13.3

before_install:
#  - brew install autoconf automake cmake opam pkg-config sqlite gmp mpfr
#  - brew cask install java
  - git clone https://github.com/andrecostea/infer.git
  - cd infer
  - ./build-infer.sh java
  - make install
  - export PATH=`pwd`/infer/bin:$PATH
  - cd ~
  - ./install_antlr.sh
  - cd ~

install:
  - mvn install:install-file -Dfile=antlr-java/target/antlr-1-jar-with-dependencies.jar  -DgroupId=org.racerdfix.antlr -DartifactId=antlr -Dversion=1.0 -Dpackaging=jar
